
export enum NetworkSymptom {
  DPI_BLOCK = 'DPI_BLOCK',
  SNI_BLOCK = 'SNI_BLOCK',
  TCP_RESET = 'TCP_RESET',
  TLS_HANDSHAKE_FAIL = 'TLS_HANDSHAKE_FAIL',
  TELEGRAM_FAIL = 'TELEGRAM_FAIL',
  WHATSAPP_FAIL = 'WHATSAPP_FAIL',
  UNKNOWN_FAIL = 'UNKNOWN_FAIL',
  DNS_POISONING = 'DNS_POISONING'
}

export enum AppTarget {
  TELEGRAM = 'TELEGRAM',
  WHATSAPP = 'WHATSAPP',
  YOUTUBE = 'YOUTUBE',
  UNIVERSAL = 'UNIVERSAL',
  UNKNOWN = 'UNKNOWN'
}

export enum RestrictionClass {
  TLS_FINGERPRINTING = 'TLS_FINGERPRINTING',
  IP_BLOCKING = 'IP_BLOCKING',
  DNS_POISONING = 'DNS_POISONING',
  PROTOCOL_WHITELISTING = 'PROTOCOL_WHITELISTING',
  PLATFORM_RESTRICTION = 'PLATFORM_RESTRICTION',
  NONE = 'NONE'
}
