/**
 * Domain Definitions
 *
 * Defines the strict vocabulary used by the Core Engine to model the network environment.
 * These types serve as the interface between the chaotic reality (User/AI input)
 * and the deterministic logic (Core).
 *
 * Implements: PROJECT_WHITEPAPER.md → Section 4.1: Input Normalization
 */

import { NetworkSymptom, AppTarget, RestrictionClass } from './enums';

export type Platform = 'android' | 'windows' | 'linux' | 'ios' | 'browser';

/**
 * DecisionInput
 *
 * The normalized representation of the user's environment.
 * The AI or UI must map raw text/forms into this rigid structure.
 *
 * Defined in PROJECT_WHITEPAPER.md → Section 4.1
 */
export interface DecisionInput {
  platform: Platform;
  targetApp: AppTarget;
  symptoms: NetworkSymptom[];
  region?: string;
}

export interface StrategyDescriptor {
  id: string;
  name: string;
  intent: string;
  riskLevel: 'safe' | 'moderate' | 'high';
  compatibility: Platform[];
}

/**
 * DecisionResult
 *
 * The deterministic output of the decision engine.
 * Contains the strategy intent, confidence score, and diagnostic explanation.
 *
 * Defined in PROJECT_WHITEPAPER.md → Section 4.4
 */
export interface DecisionResult {
  strategyId: string;
  confidence: number; // 0.0 to 1.0
  restrictionClass: RestrictionClass;
  explanation: string[];
  warnings: string[];
  tags: string[];
  meta?: Record<string, any>;
}

export interface DetectedCondition {
  type: 'restriction' | 'capability' | 'environment';
  value: string;
  weight: number;
}

export interface AnalysisResult {
  restrictionClass: RestrictionClass;
  confidence: number;
  evidence: string[];
  executionSupported: boolean;
  explanation: string[];
}

/**
 * KnowledgeSignal
 * 
 * Advisory-Only Output.
 * Generated by the Knowledge Engine, not the Decision Engine.
 * Used for UI hints and educational context, NEVER for execution logic.
 */
export interface KnowledgeSignal {
  sourceScenario: string;
  category: 'MASKING' | 'PRESSURE' | 'ENTROPY' | 'UNKNOWN';
  insight: string;
  technicalRelevance: string;
  historicalEffectiveness: number;
}