
/**
 * Domain Definitions
 *
 * Defines the strict vocabulary used by the Core Engine to model the network environment.
 * These types serve as the interface between the chaotic reality (User/AI input)
 * and the deterministic logic (Core).
 *
 * Implements: PROJECT_WHITEPAPER.md → Section 4.1: Input Normalization
 */

import { NetworkSymptom, AppTarget, RestrictionClass } from './enums';

export type Platform = 'android' | 'windows' | 'linux' | 'ios' | 'browser';

/**
 * DecisionInput
 *
 * The normalized representation of the user's environment.
 * The AI or UI must map raw text/forms into this rigid structure.
 */
export interface DecisionInput {
  platform: Platform;
  targetApp: AppTarget;
  symptoms: NetworkSymptom[];
  region?: string;
}

export interface StrategyDescriptor {
  id: string;
  name: string;
  intent: string;
  riskLevel: 'safe' | 'moderate' | 'high' | 'experimental';
  compatibility: Platform[];
  source?: 'CORE' | 'COMMUNITY'; // Origin of the strategy
}

export interface DecisionResult {
  strategyId: string;
  confidence: number; // 0.0 to 1.0
  restrictionClass: RestrictionClass;
  explanation: string[];
  warnings: string[];
  tags: string[];
  meta?: Record<string, any>;
}

export interface DetectedCondition {
  type: 'restriction' | 'capability' | 'environment';
  value: string;
  weight: number;
}

export interface AnalysisResult {
  restrictionClass: RestrictionClass;
  confidence: number;
  evidence: string[];
  executionSupported: boolean;
  explanation: string[];
}

/**
 * KnowledgeSignal
 * 
 * Advisory-Only Output.
 * Generated by the Knowledge Engine, not the Decision Engine.
 */
export interface KnowledgeSignal {
  sourceScenario: string;
  category: 'MASKING' | 'PRESSURE' | 'ENTROPY' | 'STATE' | 'UNKNOWN';
  insight: string;
  technicalRelevance: string;
  historicalEffectiveness: number;
}

export interface AdversaryProfile {
  id: string;
  name: string;
  type: 'IN_LINE' | 'ON_PATH' | 'HYBRID';
  capabilities: string[];
  knownWeaknesses: string[];
  description: string;
}

// --- KNOWLEDGE SYSTEM TYPES (v2 - Weighted Trust) ---

export type ObservationResult = 'SUCCESS' | 'FAIL' | 'UNSTABLE';

export type VerificationSource = 'ARCHITECT' | 'VERIFIED_USER' | 'ANONYMOUS' | 'AI_INFERENCE';

export interface EnvironmentContext {
  vpnActive: boolean;
  regionMatch: boolean; // Does user region match target region?
  osVersion?: string;
  networkType: 'wifi' | 'mobile' | 'wired' | 'unknown';
}

/**
 * Observation
 * Raw empirical data point from a user or probe.
 * "I tried X and Y happened."
 */
export interface Observation {
  id: string;
  timestamp: string; // ISO
  input: DecisionInput; // The logical context (Platform, Target)
  strategyId: string; // The action taken
  result: ObservationResult; // The outcome
  signals: string[]; // Specific technical signals (e.g. "timeout_after_hello")
  
  // V2: Trust & Physical Context
  verification: VerificationSource;
  trustWeight: number; // 0.0 to 1.0 (Architect=1.0, VerifiedUser=0.99, Anon=0.5)
  envContext: EnvironmentContext;
}

/**
 * KnowledgeEntry
 * A verified fact stored in the Core (Read-Only).
 */
export interface KnowledgeEntry {
  id: string;
  statement: string; // "Ozon SNI is reliable on MTS"
  confidence: number; // 0.0 - 1.0
  evidenceCount: number;
  lastVerified: string;
  tags: string[];
}

/**
 * Hypothesis
 * A candidate for knowledge, generated by the Aggregator.
 */
export interface Hypothesis {
  id: string;
  statement: string;
  supportingObservations: number;
  conflictingObservations: number;
  confidenceScore: number;
  status: 'PENDING_REVIEW' | 'REJECTED' | 'ACCEPTED';
}

// --- COMMUNITY DRIVER PROTOCOL ---

export interface CommunityStrategy {
  id: string;
  name: Record<string, string> | string; // Localized or plain string
  description: Record<string, string> | string; // Localized or plain string
  command: string;
  tags: string[];
  recommended?: boolean;
  author?: string;
  version?: string;
}

export interface CommunityDriverManifest {
  manifest_version: number;
  id: string;
  name: string;
  author: string;
  description: string;
  strategies: CommunityStrategy[];
  created_at: string;
}
