
/**
 * Domain Definitions
 *
 * Defines the strict vocabulary used by the Core Engine to model the network environment.
 * These types serve as the interface between the chaotic reality (User/AI input)
 * and the deterministic logic (Core).
 *
 * Implements: PROJECT_WHITEPAPER.md → Section 4.1: Input Normalization
 */

import { NetworkSymptom, AppTarget, RestrictionClass } from './enums';

export type Platform = 'android' | 'windows' | 'linux' | 'ios' | 'browser';

/**
 * Source Authority Hierarchy
 * Defines the weight of truth for a piece of knowledge.
 */
export enum SourceAuthority {
  ARCHITECT = 'ARCHITECT',       // Weight: 1.00 (Absolute Truth)
  VERIFIED_USER = 'VERIFIED_USER', // Weight: 0.99 (Empirical Reality)
  CONDITIONAL_USER = 'CONDITIONAL_USER', // Weight: 0.50 (Unverified/Bad Context)
  AI_REASONING = 'AI_REASONING'  // Weight: 0.10 (Hypothesis)
}

/**
 * DecisionInput
 *
 * The normalized representation of the user's environment.
 * The AI or UI must map raw text/forms into this rigid structure.
 */
export interface DecisionInput {
  platform: Platform;
  targetApp: AppTarget;
  symptoms: NetworkSymptom[];
  region?: string;
}

export interface StrategyDescriptor {
  id: string;
  name: string;
  intent: string;
  riskLevel: 'safe' | 'moderate' | 'high';
  compatibility: Platform[];
}

export interface DecisionResult {
  strategyId: string;
  confidence: number; // 0.0 to 1.0
  restrictionClass: RestrictionClass;
  explanation: string[];
  warnings: string[];
  tags: string[];
  meta?: Record<string, any>;
}

export interface DetectedCondition {
  type: 'restriction' | 'capability' | 'environment';
  value: string;
  weight: number;
}

export interface AnalysisResult {
  restrictionClass: RestrictionClass;
  confidence: number;
  evidence: string[];
  executionSupported: boolean;
  explanation: string[];
}

/**
 * KnowledgeSignal
 * 
 * Advisory-Only Output.
 * Generated by the Knowledge Engine, not the Decision Engine.
 */
export interface KnowledgeSignal {
  sourceScenario: string;
  category: 'MASKING' | 'PRESSURE' | 'ENTROPY' | 'STATE' | 'UNKNOWN';
  insight: string;
  technicalRelevance: string;
  historicalEffectiveness: number;
}

export interface AdversaryProfile {
  id: string;
  name: string;
  type: 'IN_LINE' | 'ON_PATH' | 'HYBRID';
  capabilities: string[];
  knownWeaknesses: string[];
  description: string;
}

// --- KNOWLEDGE SYSTEM TYPES (v2 - User Knowledge Base) ---

export type ObservationResult = 'SUCCESS' | 'FAIL' | 'UNSTABLE';

/**
 * Detailed User Context
 * Required for "Reality Expertise" verification.
 */
export interface ObservationContext {
  platform: Platform;
  networkType: 'wifi' | 'mobile' | 'wired' | 'unknown';
  vpnActive: boolean;
  locationRegion: string; // e.g., "RU-MOW"
  isHumanVerified: boolean; // Captcha/PoW pass
  appVersion: string;
}

/**
 * Observation
 * Raw empirical data point from a user or probe.
 * "I tried X and Y happened."
 */
export interface Observation {
  id: string;
  timestamp: string; // ISO
  authority: SourceAuthority; // Hierarchy level
  input: DecisionInput; // The logical context (Platform, Target)
  strategyId: string; // The action taken
  result: ObservationResult; // The outcome
  context: ObservationContext; // The physical reality
  signals: string[]; // Specific technical signals
}

/**
 * KnowledgeEntry
 * A verified fact stored in the Core (Read-Only).
 */
export interface KnowledgeEntry {
  id: string;
  statement: string; // "Ozon SNI is reliable on MTS"
  confidence: number; // 0.0 - 1.0
  evidenceCount: number;
  lastVerified: string;
  tags: string[];
}

/**
 * Hypothesis
 * A candidate for knowledge, generated by the Aggregator.
 */
export interface Hypothesis {
  id: string;
  statement: string;
  supportingObservations: number;
  conflictingObservations: number;
  confidenceScore: number;
  status: 'PENDING_REVIEW' | 'REJECTED' | 'ACCEPTED';
}